name: Create and publish a Docker images into ghcr.io

on:
  push:
    branches: ['dev']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
      - name: Build and push Docker image app01
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: src/app01
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/app01:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image app02
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with: 
          context: src/app02
          push: true 
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/app02:latest
          labels: ${{ steps.meta.outputs.labels }}